# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-07 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mainshow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mainshow',
        ),
        migrations.DeleteModel(
            name='Mustbuy',
        ),
        migrations.DeleteModel(
            name='Nav',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
